discord-webhook: "https://discord.com/api/webhooks/1414003674543292549/H7tpcC_fMttwdeH3etJQGnYgCIiPr44N9CtA1VzVkg46hOEsHXhQW_h5QoD_wDEEs7nu"

storage:
  type: "sqlite"
  mysql:
    host: "localhost"
    port: 3306
    database: "punishments"
    username: "root"
    password: "password"

rules:
  minor_chat_violations:
    - type: "warn"
      duration: "0"
    - type: "mute"
      duration: "1h"
    - type: "mute"
      duration: "24h"
    - type: "mute"
      duration: "3d"
    - type: "mute"
      duration: "7d"
  spam:
    - type: "warn"
      duration: "0"
    - type: "mute"
      duration: "10m"
    - type: "mute"
      duration: "30m"
    - type: "mute"
      duration: "2h"
    - type: "mute"
      duration: "1d"
  impersonation:
    - type: "warn"
      duration: "0"
    - type: "mute"
      duration: "1d"
    - type: "ban"
      duration: "3d"
    - type: "ban"
      duration: "7d"
    - type: "ban"
      duration: "30d"
  advertising:
    - type: "mute"
      duration: "1h"
    - type: "mute"
      duration: "1d"
    - type: "ban"
      duration: "3d"
    - type: "ban"
      duration: "30d"
  hacking:
    - type: "ban"
      duration: "30d"
    - type: "ban"
      duration: "0"
  griefing:
    - type: "warn"
      duration: "0"
    - type: "ban"
      duration: "1d"
    - type: "ban"
      duration: "7d"
    - type: "ban"
      duration: "30d"
  harassment:
    - type: "mute"
      duration: "1d"
    - type: "ban"
      duration: "3d"
    - type: "ban"
      duration: "30d"
    - type: "ban"
      duration: "0"