name: AutoPunish
version: '2.0.0'
main: com.alan.autoPunish.AutoPunish
api-version: '1.21'
authors: [AlanDev]
description: Automatic punishment escalation system for Minecraft servers

commands:
  punish:
    description: Punish a player based on rule violation
    usage: "§c/punish <player> <rule>"
    permission: autopunish.punish
  punishments:
    description: View punishment history for a player
    usage: "§c/punishments <player>"
    permission: autopunish.view.history
    aliases: [phistory]
  punishreload:
    description: Reload the AutoPunish configuration
    usage: "§c/punishreload"
    permission: autopunish.admin.reload
    aliases: [preload]
  severity:
    description: Check a player's punishment severity score
    usage: "§c/severity <player>"
    permission: autopunish.view.severity
  punishadmin:
    description: Manage pending punishments
    usage: "§c/punishadmin <list|approve|deny> [approvalId]"
    permission: autopunish.admin.approve
    aliases: [padmin]
  resethistory:
    description: Reset a player's violation history
    usage: "§c/resethistory <player>"
    permission: autopunish.admin.reset
    aliases: [resetviolations]
  rule: # *** NEW COMMAND ***
    description: Manage punishment rules and their tiers
    usage: "§c/rule <subcommand> [arguments]"
    permission: autopunish.admin.rules
    aliases: [rules, rulemanager]

permissions:
  # Basic permissions
  autopunish.punish:
    description: Allows using the punish command
    default: op

  # Viewing permissions
  autopunish.view.history:
    description: Allows viewing punishment history
    default: op
  autopunish.view.severity:
    description: Allows checking punishment severity scores
    default: op
  autopunish.view.*:
    description: Allows all viewing permissions
    default: op
    children:
      autopunish.view.history: true
      autopunish.view.severity: true

  # Admin permissions
  autopunish.admin.reload:
    description: Allows reloading the configuration
    default: op
  autopunish.admin.approve:
    description: Allows approving or denying punishments
    default: op
  autopunish.admin.reset:
    description: Allows resetting player violation history
    default: op
  autopunish.admin.rules: # *** NEW PERMISSION ***
    description: Allows creating, editing, and deleting punishment rules
    default: op
  autopunish.admin.senior:
    description: Senior admin permission that includes bypassing approvals
    default: false
    children:
      autopunish.admin.approve: true
      autopunish.admin.reload: true
      autopunish.admin.reset: true
      autopunish.admin.rules: true # *** ADDED TO SENIOR ADMIN ***
      autopunish.bypass.approval: true
  autopunish.admin.*:
    description: Grants all admin permissions
    default: op
    children:
      autopunish.admin.reload: true
      autopunish.admin.approve: true
      autopunish.admin.reset: true
      autopunish.admin.rules: true # *** ADDED TO ADMIN WILDCARD ***

  # Bypass permissions
  autopunish.bypass.approval:
    description: Allows bypassing the punishment approval system
    default: false

  # Special permissions
  autopunish.muted:
    description: Flag for muted players
    default: false

  # Comprehensive permission sets
  autopunish.staff:
    description: Basic staff permission set
    default: op
    children:
      autopunish.punish: true
      autopunish.view.*: true
  autopunish.*:
    description: Grants all AutoPunish permissions
    default: false
    children:
      autopunish.punish: true
      autopunish.view.*: true
      autopunish.admin.*: true
      autopunish.bypass.approval: true